default:
  report_maintainer: "Kelsey Dowling"
  pipeline_maintainer: "Jake Peters"
  bucket: "ccc_weekly_metrics_report"
  test_box_folders: 
    - "222593912729"
  gcp_info:
    cloud_build_trigger: ccc-module-metrics
    cloud_run: ccc-module-metrics-api

weekly_module_metrics:
  rmd_file_name: "CCC Weekly Module Metrics_RMD.Rmd"
  report_file_name: "CCC_Weekly_Module_Metrics.pdf"
  box_folders:
    - "141543281606" # internal
  gcp_info:
    cloud_scheduler: ccc-weekly-module-metrics
    frequency: "0 11 * * 1" # every Monday at 11 AM"

mod1_stats:
  rmd_file_name: "Merged Module 1 Summary Statistics.Rmd"
  report_file_name: "Merged_Module_1_Summary_Statistics.pdf"
  box_folders:
    - "208053733985"
  gcp_info:
    cloud_scheduler: ccc-module1-statistics
    frequency: "30 11 1 * *" # first of the month at 11:30 AM

mod2_stats:
  rmd_file_name: "Merged Module 2 Summary Statistics.Rmd"
  report_file_name: "Merged_Module_2_Summary_Statistics.pdf"
  box_folders:
    - "208055378225"
  gcp_info:
    cloud_scheduler: ccc-module2-statistics
    frequency: "0 12 1 * *" # first of the month at 12 PM

mod3_stats:
  rmd_file_name: "Module 3 Summary Statatistics.Rmd"
  report_file_name: "Module_3_Summary_Statatistics.pdf"
  box_folders:
    - "208062917930"
  gcp_info:
    cloud_scheduler: ccc-module3-statistics
    frequency: "30 12 1 * *" # first of the month at 12:30 PM

mod4_stats:
  rmd_file_name: "Module 4 Missingness Analysis.Rmd"
  report_file_name: "Module_4_Missingness_Analysis.pdf"
  box_folders:
    - "208060974530"
  gcp_info:
    cloud_scheduler: ccc-module4-statistics
    frequency: "0 13 1 * *" # first of the month at 1 PM

baseline_high_priority:
  rmd_file_name: "Baseline Ranked Variables- High Priority.Rmd"
  report_file_name: "Baseline_Ranked_Varialbes_High_Priority.pdf"
  box_folders:
    - "219595986209"
  gcp_info:
    cloud_scheduler: ccc-baseline-ranked-variables-high-priority
    frequency: "30 13 1 * *" # first of the month at 1:30 PM

baseline_low_priority:
  rmd_file_name: "Baseline Ranked Variables- Low Priority.Rmd"
  report_file_name: "Baseline_Ranked_Variables_Low_Priority.pdf"
  box_folders:
    - "219761433401"
  gcp_info:
    cloud_scheduler: ccc-baseline-ranked-variables-low-priority
    frequency: "30 14 1 * *" # first of the month at 2:30 PM
    
module1_qc_metrics:
  rmd_file_name: "Module 1 Custom QC Rules.Rmd"
  report_file_name: "Module_1_Custom_QC_Rules.pdf"
  box_folders:
    - "203464977998" # internal
  gcp_info:
    cloud_scheduler: ccc-module1-qc-metrics
    frequency: "45 13 * * 1" # every Monday at 1:30 PM"

recruitment_qc_metrics:
  rmd_file_name: "Rectruitment Derived Variable QC.Rmd"
  report_file_name: "Rectruitment_Derived_Variable_QC.pdf"
  box_folders:
    - "194196493018" # internal
  gcp_info:
    cloud_scheduler: ccc-recruitment-qc-metrics
    frequency: "30 13 * * 1" # every Monday at 1:30 PM"
